# Generated by Django 4.1 on 2024-03-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='skills', verbose_name='Imagen')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'habilidades',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('obtained_title', models.CharField(max_length=150, verbose_name='Título obtenido')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('date_of_realization', models.DateField(verbose_name='Fecha de realización')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
            ],
            options={
                'verbose_name': 'formacion',
                'verbose_name_plural': 'formaciones',
                'ordering': ['-date_of_realization'],
            },
        ),
    ]
