# Generated by Django 5.0.2 on 2024-03-12 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-created'], 'verbose_name': 'conocimiento', 'verbose_name_plural': 'conocimientos'},
        ),
        migrations.AddField(
            model_name='skill',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha modificación'),
        ),
    ]
