# Generated by Django 4.2.8 on 2024-05-28 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backgrounds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backgroundimage',
            options={'verbose_name': 'imagen de fondo', 'verbose_name_plural': 'imágenes de fondo'},
        ),
        migrations.RemoveField(
            model_name='backgroundimage',
            name='updated',
        ),
    ]
