# Generated by Django 4.2.8 on 2024-05-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backgrounds', '0002_alter_backgroundimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundimage',
            name='name',
            field=models.CharField(default=1, max_length=150, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
