# Generated by Django 4.2.8 on 2024-06-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backgrounds', '0002_backgroundimage_subtitle_backgroundimage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundimage',
            name='_original_imagen_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
