# Generated by Django 4.2.8 on 2024-06-06 17:01

import backgrounds.custom_storage
import backgrounds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backgrounds', '0004_remove_backgroundimage__original_imagen_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backgroundimage',
            options={'verbose_name': 'titular e imagen de fondo', 'verbose_name_plural': 'titulares e imágenes de fondo'},
        ),
        migrations.AddField(
            model_name='backgroundimage',
            name='sentence',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Frase'),
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='image',
            field=models.ImageField(storage=backgrounds.custom_storage.OverwriteStorage(), upload_to=backgrounds.models.profile_picture_path, verbose_name='Imagen'),
        ),
    ]
