# Generated by Django 4.2.8 on 2024-06-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backgrounds', '0005_alter_backgroundimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='sentence',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Frase'),
        ),
    ]
