# Generated by Django 4.2.8 on 2024-05-28 17:06

import backgrounds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backgrounds', '0005_alter_backgroundimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='image',
            field=models.ImageField(upload_to=backgrounds.models.profile_picture_path, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre'),
        ),
    ]
