# Generated by Django 4.2.8 on 2024-05-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backgrounds', '0006_alter_backgroundimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
    ]
