# Generated by Django 4.2.8 on 2024-06-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['created'], 'verbose_name': 'formación', 'verbose_name_plural': 'formaciones'},
        ),
    ]
