# Generated by Django 4.1.1 on 2024-04-28 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_options_alter_project_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='detalle',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Detalle'),
            preserve_default=False,
        ),
    ]
