# Generated by Django 4.1.1 on 2024-04-28 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(450)], verbose_name='Descripción'),
        ),
    ]
