# Generated by Django 4.1.1 on 2024-04-29 17:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='autor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='autor'),
        ),
        migrations.AddField(
            model_name='project',
            name='pie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='pie'),
        ),
        migrations.AlterField(
            model_name='project',
            name='detalle',
            field=ckeditor.fields.RichTextField(verbose_name='Detalle'),
        ),
    ]
