# Generated by Django 4.1.1 on 2024-05-02 18:13

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_project_autor_project_pie_alter_project_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=portfolio.models.profile_picture_path, verbose_name='Imagen'),
        ),
    ]
