# Generated by Django 4.2.8 on 2024-05-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link_i',
            field=models.URLField(blank=True, max_length=180, null=True, verbose_name='Enlace Web'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, max_length=180, null=True, verbose_name='Enlace Github'),
        ),
    ]
